language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
before_install:
        - pip3 install Cython numpy
        - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz -q
        - tar -xzf ta-lib-0.4.0-src.tar.gz
        - cd ta-lib/ 
        - ./configure --prefix=/usr
        - make
        - sudo make install
# command to install dependencies
install:
  - git clone https://github.com/jesse-ai/jesse jesse
  - cd jesse
  - pip install -r requirements.txt
  
# command to run tests
script:
  - pytest
